# Generated by Django 4.1 on 2022-08-23 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Заголовок")),
                ("text", models.TextField(max_length=10000, verbose_name="Содержание")),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photos_of_article/%Y/%m/%d", verbose_name="Фото"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size_num", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Sneaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sneaker", models.CharField(max_length=30, verbose_name="Кроссовки")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="URL"),
                ),
                ("photo", models.ImageField(upload_to="photos_of_sneaker/%Y/%m/%d")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Цена"
                    ),
                ),
                (
                    "articles",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="life_style.article",
                        verbose_name="Статьи",
                    ),
                ),
                (
                    "brands",
                    models.ManyToManyField(to="life_style.brand", verbose_name="Бренд"),
                ),
                (
                    "sizes",
                    models.ManyToManyField(to="life_style.size", verbose_name="Размер"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=5000, verbose_name="Отзыв")),
                (
                    "sneaker",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="life_style.sneaker",
                        verbose_name="Кроссовки",
                    ),
                ),
            ],
        ),
    ]
