# Generated by Django 4.1 on 2022-08-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("life_style", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Статьи", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"verbose_name": "Бренды", "verbose_name_plural": "Бренды"},
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={"verbose_name": "Отзывы", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name": "Размеры", "verbose_name_plural": "Размеры"},
        ),
        migrations.AlterModelOptions(
            name="sneaker",
            options={"verbose_name": "Кроссовки", "verbose_name_plural": "Кроссовки"},
        ),
    ]
